### ISSUE TITLE
Question about picture pre-segment for PASTIS

### ISSUE THREAD

**Issue by zkjisj** [michaeltrs/DeepSatModels#14]
It's nice to see your wonderful work. However, in your literature, I noticed that you split one 128×128 patch in PASTIS to 25 24×24 patches. This seems to be questionable for you abandon extra pixels. When I take use of your model for PASTIS, I split one 128×128 patch to 16 32×32 patches, the training results is apparently worse than in PASTIS24. The comparative experiment seems to be unfair in your paper, I wonder to know if you tested other models on PASTIS24?

**Comment by michaeltrs** [comment]
Hi @zkjisj,

This is not a problem because all pixels, included or not, come from the same distribution. In fact because missing pixels are uniformly spread throughout the AOI their effect is minimal. This has been tested by taking size 36x24x24 patches that cover the entire extent, and masking accordingly to avoid double counted pixels, performance was the same. Equivalently, evaluating on  random subsets of the test set leads to similar performances as reported. Regarding results with size 32 patches, I cannot say for certain. However, if you reduce the batch size to fit larger input into gpu that could be an issue.

All models presented in Table 2 of our paper were retrained with consistent data and settings as detailed in Section 4.1 (Implementation Details). This can also be seen by reported  number of iterations/s which correspond to size 24 inputs.

**Comment by zkjisj** [comment]
Thanks for your reply, it helps a lot!
